# segment_map.py

Segment_map = {
    'A': frozenset('A B C F E G1 G2'.split()),
    'B': frozenset('A B C D I L G2'.split()),
    'C': frozenset('A F E D'.split()),
    'D': frozenset('A B C D I L'.split()),
    'E': frozenset('A F G1 E D'.split()),
    'F': frozenset('A F G1 E'.split()),
    'G': frozenset('A F G2 E C D'.split()),
    'H': frozenset('F B G1 G2 E C'.split()),
    'I': frozenset('A I L D'.split()),
    'J': frozenset('A I M E'.split()),
    'K': frozenset('F J G1 E K'.split()),
    'L': frozenset('F E D'.split()),
    'M': frozenset('F H J B E C'.split()),
    'N': frozenset('F H B E K C'.split()),
    'O': frozenset('A F B E C D'.split()),
    'P': frozenset('A F B G1 G2 E'.split()),
    'Q': frozenset('A F B E K C D'.split()),
    'R': frozenset('A F B G1 G2 E K'.split()),
    'S': frozenset('A H G2 C D'.split()),
    'T': frozenset('A I L'.split()),
    'U': frozenset('F B E C D'.split()),
    'V': frozenset('H B K C'.split()),
    'W': frozenset('F B E M K C'.split()),
    'X': frozenset('H J M K'.split()),
    'Y': frozenset('H J L'.split()),
    'Z': frozenset('A J M D'.split()),
    '0': frozenset('A F J B E M C D'.split()),
    '1': frozenset('I L'.split()),
    '2': frozenset('A B G2 M D'.split()),
    '3': frozenset('A B G2 C D'.split()),
    '4': frozenset('F B G1 G2 C'.split()),
    '5': frozenset('A F G1 G2 C D'.split()),
    '6': frozenset('A F G1 G2 E C D'.split()),
    '7': frozenset('A J M'.split()),
    '8': frozenset('A F B G1 G2 E C D'.split()),
    '9': frozenset('A F B G1 G2 C D'.split()),
    '~': frozenset('F H B'.split()),
    '`': frozenset('H'.split()),
    '@': frozenset('A B C D E L G1'.split()),
    '$': frozenset('A C D F G1 G2 I L'.split()),
    '^': frozenset('F H'.split()),
    '*': frozenset('H I J K L M'.split()),
    '(': frozenset('J K'.split()),
    ')': frozenset('H M'.split()),
    '_': frozenset('D'.split()),
    '-': frozenset('G1 G2'.split()),
    '+': frozenset('I L G1 G2'.split()),
    '=': frozenset('G1 G2 D'.split()),
    '{': frozenset('J K G1'.split()),
    '}': frozenset('H M G2'.split()),
    '|': frozenset('I L'.split()),
    '\\': frozenset('H K'.split()),
    '"': frozenset('I B'.split()),
    "'": frozenset('J'.split()),
    '<': frozenset('J K'.split()),
    '>': frozenset('H M'.split()),
    '/': frozenset('J M'.split()),
    'unknown': frozenset('A B C D E F H J M K'.split()),
    ' ': frozenset(),
    '\t': frozenset()
}
